import React, {
  useState,
  useEffect,
  useRef,
  useCallback,
  useMemo,
} from "react";
import {
  QrCode,
  UserPlus,
  ScanLine,
  LayoutDashboard,
  Download,
  CheckCircle2,
  XCircle,
  AlertTriangle,
  Search,
  Users,
  UserCheck,
  UserX,
  Camera,
  CameraOff,
  KeyRound,
  X,
  Moon,
  Sun,
  Lock,
  ShieldCheck,
  RefreshCw,
  ImagePlus,
} from "lucide-react";
import { Html5Qrcode } from "html5-qrcode";
import QRCode from "qrcode";
import confetti from "canvas-confetti";

/**
 * ─────────────────────────────────────────────────────────────────────────
 *  QR-BASED EVENT CHECK-IN SYSTEM — hardened build
 * ─────────────────────────────────────────────────────────────────────────
 *  npm install html5-qrcode qrcode canvas-confetti lucide-react
 *
 *  SECURITY NOTE (read before real deployment):
 *  QR_SECRET and ADMIN_PIN below live in the client-side JS bundle, so
 *  anyone who opens devtools and reads the bundled source can find them.
 *  That's fine for stopping casual fraud (typed IDs, copy-pasted payloads,
 *  screenshots edited in Photoshop) at a college/office event, but it is
 *  NOT cryptographically airtight. For a fully tamper-proof system, move
 *  signing + verification to a small backend (Firebase Function, Supabase
 *  Edge Function, etc.) so the secret never ships to the browser.
 *
 *  Data model (persisted to localStorage under STORAGE_KEY):
 *  {
 *    id: string,
 *    name: string,
 *    email: string,
 *    photo: string,          // base64 JPEG data URL, captured at registration
 *    attended: boolean,
 *    checkedInAt: string | null
 *  }
 * ─────────────────────────────────────────────────────────────────────────
 */

const STORAGE_KEY = "eventCheckIn.participants.v2";
const THEME_KEY = "eventCheckIn.theme.v1";
const ADMIN_AUTH_KEY = "eventCheckIn.adminAuthed.v1"; // sessionStorage — cleared when tab closes

// CHANGE BOTH OF THESE BEFORE DEPLOYING. Keep them out of your public repo
// if possible (e.g. inject via a build-time env var instead of hardcoding).
const QR_SECRET = "change-this-secret-before-you-deploy-2026";
const ADMIN_PIN = "2468";

const MAX_PIN_ATTEMPTS = 5;
const PIN_LOCKOUT_MS = 30_000;

// ────────────────────────────────────────────────────────────────────────
// Small utilities
// ────────────────────────────────────────────────────────────────────────
function generateId() {
  return `TCK-${Date.now().toString(36).toUpperCase()}-${Math.random()
    .toString(36)
    .slice(2, 6)
    .toUpperCase()}`;
}

function formatTime(isoString) {
  if (!isoString) return "";
  const d = new Date(isoString);
  return d.toLocaleString(undefined, {
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    day: "2-digit",
    month: "short",
  });
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  let binary = "";
  bytes.forEach((b) => (binary += String.fromCharCode(b)));
  return btoa(binary);
}

// Signs `${id}|${name}|${email}` with HMAC-SHA256 so a hand-typed or edited
// payload can be told apart from one that was genuinely generated by this app.
async function hmacSign(message, secret) {
  const enc = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sigBuffer = await crypto.subtle.sign("HMAC", key, enc.encode(message));
  return arrayBufferToBase64(sigBuffer);
}

async function signPayload({ id, name, email }) {
  const sig = await hmacSign(`${id}|${name}|${email}`, QR_SECRET);
  return { id, name, email, sig };
}

async function verifySignature(payload) {
  if (!payload || !payload.id || !payload.name || !payload.email || !payload.sig) {
    return false;
  }
  const expected = await hmacSign(`${payload.id}|${payload.name}|${payload.email}`, QR_SECRET);
  return expected === payload.sig;
}

// Web Audio beeps — no external audio asset needed.
function playBeep({ frequency = 880, duration = 150, type = "sine" } = {}) {
  try {
    const AudioCtx = window.AudioContext || window.webkitAudioContext;
    if (!AudioCtx) return;
    const ctx = new AudioCtx();
    const oscillator = ctx.createOscillator();
    const gain = ctx.createGain();
    oscillator.type = type;
    oscillator.frequency.value = frequency;
    gain.gain.setValueAtTime(0.15, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + duration / 1000);
    oscillator.connect(gain);
    gain.connect(ctx.destination);
    oscillator.start();
    oscillator.stop(ctx.currentTime + duration / 1000);
    oscillator.onended = () => ctx.close();
  } catch {
    // Audio isn't critical to the flow — fail silently if unsupported/blocked.
  }
}
function playSuccessBeep() {
  playBeep({ frequency: 880, duration: 120, type: "sine" });
  setTimeout(() => playBeep({ frequency: 1180, duration: 160, type: "sine" }), 120);
}
function playErrorBeep() {
  playBeep({ frequency: 220, duration: 220, type: "square" });
}
function fireConfetti() {
  confetti({ particleCount: 120, spread: 75, origin: { y: 0.6 }, zIndex: 9999 });
  confetti({ particleCount: 60, angle: 60, spread: 55, origin: { x: 0, y: 0.7 }, zIndex: 9999 });
  confetti({ particleCount: 60, angle: 120, spread: 55, origin: { x: 1, y: 0.7 }, zIndex: 9999 });
}

// Resizes/crops any image source (video frame or uploaded file) down to a
// small square JPEG data URL, so photos don't bloat localStorage.
function drawSquareToDataUrl(source, sw, sh, size = 240) {
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext("2d");
  const s = Math.min(sw, sh);
  ctx.drawImage(source, (sw - s) / 2, (sh - s) / 2, s, s, 0, 0, size, size);
  return canvas.toDataURL("image/jpeg", 0.82);
}

// ────────────────────────────────────────────────────────────────────────
// Persistence hook
// ────────────────────────────────────────────────────────────────────────
function useParticipants() {
  const [participants, setParticipants] = useState(() => {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      return raw ? JSON.parse(raw) : [];
    } catch {
      return [];
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(participants));
    } catch {
      // Storage full/blocked — ignore. Photos are the biggest space cost;
      // if this becomes a real problem, move photos to a backend instead
      // of localStorage.
    }
  }, [participants]);

  return [participants, setParticipants];
}

// ────────────────────────────────────────────────────────────────────────
// Root component
// ────────────────────────────────────────────────────────────────────────
export default function App() {
  const [participants, setParticipants] = useParticipants();
  const [activeTab, setActiveTab] = useState("register");
  const [isDark, setIsDark] = useState(() => {
    const saved = localStorage.getItem(THEME_KEY);
    return saved ? saved === "dark" : true;
  });

  useEffect(() => {
    document.documentElement.classList.toggle("dark", isDark);
    localStorage.setItem(THEME_KEY, isDark ? "dark" : "light");
  }, [isDark]);

  // Always-fresh ref to participants, so async scan resolution never reads
  // a stale closure value.
  const participantsRef = useRef(participants);
  useEffect(() => {
    participantsRef.current = participants;
  }, [participants]);

  const registerParticipant = useCallback(
    (data) => {
      const record = {
        id: data.id || generateId(),
        name: data.name.trim(),
        email: data.email.trim(),
        photo: data.photo,
        attended: false,
        checkedInAt: null,
      };
      setParticipants((prev) => [...prev, record]);
      return record;
    },
    [setParticipants]
  );

  // STEP 1 of check-in: verify the signature and look the ticket up, but do
  // NOT mark attendance yet. This lets the scanner pause and show the admin
  // a photo to confirm before anything is committed.
  const resolveScan = useCallback(async (payloadString) => {
    let payload;
    try {
      payload = JSON.parse(payloadString);
    } catch {
      return { status: "invalid", reason: "This doesn't look like a valid QR ticket." };
    }
    if (!payload || typeof payload !== "object" || !payload.id) {
      return { status: "invalid", reason: "QR payload is missing required fields." };
    }

    const validSig = await verifySignature(payload);
    if (!validSig) {
      return {
        status: "invalid",
        reason:
          "Signature check failed. This ticket may be hand-typed, edited, or copied rather than a real scanned QR.",
      };
    }

    const existing = participantsRef.current.find((p) => p.id === payload.id);
    if (!existing) {
      return { status: "invalid", reason: "This ticket ID is not registered for this event." };
    }
    if (existing.attended) {
      return { status: "duplicate", participant: existing };
    }
    return { status: "pending-confirm", participant: existing };
  }, []);

  // STEP 2: only called after the admin visually confirms the photo matches
  // the person in front of them.
  const commitCheckIn = useCallback(
    (id) => {
      let updated = null;
      setParticipants((prev) => {
        const idx = prev.findIndex((p) => p.id === id);
        if (idx === -1) return prev;
        const checkedInAt = new Date().toISOString();
        updated = { ...prev[idx], attended: true, checkedInAt };
        const next = [...prev];
        next[idx] = updated;
        return next;
      });
      return updated;
    },
    [setParticipants]
  );

  const stats = useMemo(() => {
    const total = participants.length;
    const attended = participants.filter((p) => p.attended).length;
    const pending = total - attended;
    const pct = total === 0 ? 0 : Math.round((attended / total) * 100);
    return { total, attended, pending, pct };
  }, [participants]);

  const tabs = [
    { id: "register", label: "Register Participant", icon: UserPlus },
    { id: "scan", label: "Admin QR Scanner", icon: ScanLine },
    { id: "dashboard", label: "Attendance Dashboard", icon: LayoutDashboard },
  ];

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900 dark:bg-slate-950 dark:text-slate-100 transition-colors">
      <header className="sticky top-0 z-30 border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-950/80 backdrop-blur">
        <div className="mx-auto max-w-6xl px-4 sm:px-6 py-4 flex items-center justify-between gap-4">
          <div className="flex items-center gap-2.5">
            <div className="h-9 w-9 rounded-xl bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-600/30">
              <QrCode className="h-5 w-5 text-white" />
            </div>
            <div>
              <h1 className="text-base sm:text-lg font-semibold leading-tight">Event Check-In</h1>
              <p className="text-xs text-slate-500 dark:text-slate-400 leading-tight hidden sm:block">
                Signed QR tickets · photo-verified entry
              </p>
            </div>
          </div>

          <button
            onClick={() => setIsDark((d) => !d)}
            aria-label="Toggle dark mode"
            className="h-9 w-9 rounded-lg border border-slate-200 dark:border-slate-800 flex items-center justify-center hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
          >
            {isDark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          </button>
        </div>

        <nav className="mx-auto max-w-6xl px-4 sm:px-6 flex gap-1 overflow-x-auto pb-2 -mt-1">
          {tabs.map((tab) => {
            const Icon = tab.icon;
            const active = activeTab === tab.id;
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTab(tab.id)}
                className={`flex items-center gap-1.5 whitespace-nowrap rounded-lg px-3 py-1.5 text-sm font-medium transition-colors ${
                  active
                    ? "bg-indigo-600 text-white shadow shadow-indigo-600/30"
                    : "text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"
                }`}
              >
                <Icon className="h-4 w-4" />
                {tab.label}
              </button>
            );
          })}
        </nav>
      </header>

      <div className="mx-auto max-w-6xl px-4 sm:px-6 pt-6">
        <StatsCards stats={stats} />
      </div>

      <main className="mx-auto max-w-6xl px-4 sm:px-6 py-6">
        {activeTab === "register" && <RegisterParticipant onRegister={registerParticipant} />}
        {activeTab === "scan" && (
          <AdminScanner resolveScan={resolveScan} commitCheckIn={commitCheckIn} />
        )}
        {activeTab === "dashboard" && <AttendanceDashboard participants={participants} />}
      </main>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Stats Cards
// ────────────────────────────────────────────────────────────────────────
function StatsCards({ stats }) {
  const cards = [
    { label: "Total Registered", value: stats.total, icon: Users, color: "text-indigo-600 dark:text-indigo-400", bar: "bg-indigo-600" },
    { label: "Checked In", value: stats.attended, icon: UserCheck, color: "text-emerald-600 dark:text-emerald-400", bar: "bg-emerald-600" },
    { label: "Remaining", value: stats.pending, icon: UserX, color: "text-amber-600 dark:text-amber-400", bar: "bg-amber-500" },
  ];

  return (
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
      {cards.map((c) => {
        const Icon = c.icon;
        const pct = stats.total === 0 ? 0 : Math.round((c.value / stats.total) * 100);
        return (
          <div key={c.label} className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 shadow-sm">
            <div className="flex items-center justify-between">
              <span className="text-sm text-slate-500 dark:text-slate-400">{c.label}</span>
              <Icon className={`h-4 w-4 ${c.color}`} />
            </div>
            <div className="mt-1 flex items-end gap-2">
              <span className="text-2xl font-bold tabular-nums">{c.value}</span>
              <span className="text-xs text-slate-400 mb-1">{pct}%</span>
            </div>
            <div className="mt-3 h-1.5 w-full rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
              <div className={`h-full rounded-full ${c.bar} transition-all duration-500`} style={{ width: `${pct}%` }} />
            </div>
          </div>
        );
      })}
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Photo capture — used at registration. Live camera preferred, file upload
// as a fallback for devices without one / permission denied.
// ────────────────────────────────────────────────────────────────────────
function PhotoCapture({ value, onChange, error }) {
  const videoRef = useRef(null);
  const streamRef = useRef(null);
  const [cameraOn, setCameraOn] = useState(false);
  const [camError, setCamError] = useState(null);

  async function startCamera() {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user" } });
      streamRef.current = stream;
      // Just flip the flag here — the <video> element doesn't exist in the
      // DOM yet on this render pass (cameraOn was still false when this
      // function started), so we attach the stream in the effect below,
      // which runs *after* React has actually mounted the <video> tag.
      setCameraOn(true);
      setCamError(null);
    } catch {
      setCamError("Camera unavailable — upload a photo instead.");
    }
  }

  // Runs after the <video> element is in the DOM (cameraOn just flipped to
  // true), so videoRef.current is guaranteed to exist here.
  useEffect(() => {
    if (cameraOn && videoRef.current && streamRef.current) {
      videoRef.current.srcObject = streamRef.current;
      videoRef.current.play().catch(() => {
        // Autoplay can be blocked in rare cases — the visible "Capture"
        // button still lets the user try again after interacting with the page.
      });
    }
  }, [cameraOn]);

  function stopCamera() {
    streamRef.current?.getTracks().forEach((t) => t.stop());
    streamRef.current = null;
    setCameraOn(false);
  }

  // Always release the camera when this component goes away.
  useEffect(() => () => stopCamera(), []);

  function capture() {
    const video = videoRef.current;
    if (!video || !video.videoWidth) return;
    const dataUrl = drawSquareToDataUrl(video, video.videoWidth, video.videoHeight);
    onChange(dataUrl);
    stopCamera();
  }

  function handleFile(e) {
    const file = e.target.files?.[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        onChange(drawSquareToDataUrl(img, img.width, img.height));
      };
      img.src = reader.result;
    };
    reader.readAsDataURL(file);
  }

  return (
    <div>
      <label className="text-sm font-medium">Photo (required for identity verification)</label>

      {value ? (
        <div className="mt-2 flex items-center gap-3">
          <img src={value} alt="Captured" className="h-20 w-20 rounded-xl object-cover border border-slate-200 dark:border-slate-800" />
          <button
            type="button"
            onClick={() => onChange(null)}
            className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-medium px-3 py-1.5"
          >
            <RefreshCw className="h-3.5 w-3.5" />
            Retake
          </button>
        </div>
      ) : (
        <div className="mt-2 space-y-2">
          {cameraOn ? (
            <div className="space-y-2">
              <video ref={videoRef} muted playsInline className="w-40 h-40 rounded-xl object-cover border border-slate-200 dark:border-slate-800 bg-black" />
              <div className="flex gap-2">
                <button type="button" onClick={capture} className="rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-medium px-3 py-1.5">
                  Capture
                </button>
                <button type="button" onClick={stopCamera} className="rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-medium px-3 py-1.5">
                  Cancel
                </button>
              </div>
            </div>
          ) : (
            <div className="flex flex-wrap gap-2">
              <button type="button" onClick={startCamera} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-medium px-3 py-1.5">
                <Camera className="h-3.5 w-3.5" />
                Use camera
              </button>
              <label className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-xs font-medium px-3 py-1.5 cursor-pointer">
                <ImagePlus className="h-3.5 w-3.5" />
                Upload photo
                <input type="file" accept="image/*" onChange={handleFile} className="hidden" />
              </label>
            </div>
          )}
          {camError && <p className="text-xs text-slate-400">{camError}</p>}
        </div>
      )}
      {error && <p className="text-xs text-red-500 mt-1">{error}</p>}
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Tab 1 — Register Participant
// ────────────────────────────────────────────────────────────────────────
function RegisterParticipant({ onRegister }) {
  const [form, setForm] = useState({ name: "", email: "", rollId: "" });
  const [photo, setPhoto] = useState(null);
  const [errors, setErrors] = useState({});
  const [registered, setRegistered] = useState(null);
  const [qrDataUrl, setQrDataUrl] = useState(null);
  const [submitting, setSubmitting] = useState(false);

  function validate() {
    const next = {};
    if (!form.name.trim()) next.name = "Name is required.";
    if (!form.email.trim()) {
      next.email = "Email is required.";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email.trim())) {
      next.email = "Enter a valid email address.";
    }
    if (!photo) next.photo = "A photo is required so admins can verify identity at check-in.";
    setErrors(next);
    return Object.keys(next).length === 0;
  }

  async function handleSubmit(e) {
    e.preventDefault();
    if (!validate()) return;
    setSubmitting(true);

    try {
      const record = onRegister({
        id: form.rollId.trim() || undefined,
        name: form.name,
        email: form.email,
        photo,
      });

      // The QR only ever carries id/name/email/signature — never the photo.
      // Keeps the QR scannable and small; the photo is looked up locally
      // from the registered record at scan time.
      const signed = await signPayload({ id: record.id, name: record.name, email: record.email });
      const payload = JSON.stringify(signed);

      const dataUrl = await QRCode.toDataURL(payload, {
        width: 320,
        margin: 2,
        color: { dark: "#1e1b4b", light: "#ffffff" },
      });
      setQrDataUrl(dataUrl);
      setRegistered(record);
    } catch {
      setErrors({ form: "Could not generate QR code. Please try again." });
    } finally {
      setSubmitting(false);
    }
  }

  function handleDownload() {
    if (!qrDataUrl || !registered) return;
    const link = document.createElement("a");
    link.href = qrDataUrl;
    link.download = `qr-${registered.id}.png`;
    link.click();
  }

  function handleRegisterAnother() {
    setForm({ name: "", email: "", rollId: "" });
    setPhoto(null);
    setErrors({});
    setRegistered(null);
    setQrDataUrl(null);
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm">
        <h2 className="text-lg font-semibold flex items-center gap-2">
          <UserPlus className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
          Register Participant
        </h2>
        <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
          Each submission generates a cryptographically signed, photo-linked QR ticket.
        </p>

        <form onSubmit={handleSubmit} className="mt-5 space-y-4">
          <div>
            <label className="text-sm font-medium">Full Name</label>
            <input
              type="text"
              value={form.name}
              onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
              placeholder="e.g. Priya Sharma"
              className={`mt-1 w-full rounded-lg border bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500 ${errors.name ? "border-red-400" : "border-slate-200 dark:border-slate-800"}`}
            />
            {errors.name && <p className="text-xs text-red-500 mt-1">{errors.name}</p>}
          </div>

          <div>
            <label className="text-sm font-medium">Email</label>
            <input
              type="email"
              value={form.email}
              onChange={(e) => setForm((f) => ({ ...f, email: e.target.value }))}
              placeholder="priya@example.com"
              className={`mt-1 w-full rounded-lg border bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500 ${errors.email ? "border-red-400" : "border-slate-200 dark:border-slate-800"}`}
            />
            {errors.email && <p className="text-xs text-red-500 mt-1">{errors.email}</p>}
          </div>

          <div>
            <label className="text-sm font-medium">
              Roll / Ticket ID <span className="text-slate-400 font-normal">(optional)</span>
            </label>
            <input
              type="text"
              value={form.rollId}
              onChange={(e) => setForm((f) => ({ ...f, rollId: e.target.value }))}
              placeholder="Leave blank to auto-generate"
              className="mt-1 w-full rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>

          <PhotoCapture value={photo} onChange={setPhoto} error={errors.photo} />

          {errors.form && <p className="text-xs text-red-500">{errors.form}</p>}

          <button
            type="submit"
            disabled={submitting}
            className="w-full rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-60 text-white text-sm font-medium py-2.5 transition-colors shadow shadow-indigo-600/30"
          >
            {submitting ? "Generating…" : "Generate QR Ticket"}
          </button>
        </form>
      </div>

      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm flex flex-col items-center justify-center text-center min-h-[400px]">
        {!registered && (
          <div className="text-slate-400 dark:text-slate-600">
            <QrCode className="h-16 w-16 mx-auto mb-3 opacity-40" />
            <p className="text-sm">Your generated QR ticket will appear here.</p>
          </div>
        )}

        {registered && qrDataUrl && (
          <div className="w-full">
            <img src={registered.photo} alt={registered.name} className="mx-auto h-16 w-16 rounded-full object-cover border border-slate-200 dark:border-slate-800 mb-3" />
            <img src={qrDataUrl} alt={`QR ticket for ${registered.name}`} className="mx-auto rounded-xl border border-slate-200 dark:border-slate-800 bg-white p-2 w-52 h-52" />
            <div className="mt-4 space-y-0.5">
              <p className="font-semibold">{registered.name}</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">{registered.email}</p>
              <p className="text-xs font-mono text-indigo-600 dark:text-indigo-400 mt-1">{registered.id}</p>
            </div>

            <div className="mt-5 flex flex-col sm:flex-row gap-2 justify-center">
              <button onClick={handleDownload} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium px-4 py-2 transition-colors">
                <Download className="h-4 w-4" />
                Download QR
              </button>
              <button onClick={handleRegisterAnother} className="inline-flex items-center justify-center gap-1.5 rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-sm font-medium px-4 py-2 transition-colors">
                Register Another
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Admin PIN gate — wraps the whole scanner tab
// ────────────────────────────────────────────────────────────────────────
function AdminPinGate({ children }) {
  const [authed, setAuthed] = useState(() => sessionStorage.getItem(ADMIN_AUTH_KEY) === "true");
  const [pin, setPin] = useState("");
  const [attempts, setAttempts] = useState(0);
  const [lockedUntil, setLockedUntil] = useState(0);
  const [now, setNow] = useState(Date.now());

  useEffect(() => {
    if (!lockedUntil) return;
    const t = setInterval(() => setNow(Date.now()), 500);
    return () => clearInterval(t);
  }, [lockedUntil]);

  const locked = lockedUntil > now;
  const secondsLeft = Math.ceil((lockedUntil - now) / 1000);

  function handleSubmit(e) {
    e.preventDefault();
    if (locked) return;
    if (pin === ADMIN_PIN) {
      sessionStorage.setItem(ADMIN_AUTH_KEY, "true");
      setAuthed(true);
      return;
    }
    const nextAttempts = attempts + 1;
    setAttempts(nextAttempts);
    setPin("");
    if (nextAttempts >= MAX_PIN_ATTEMPTS) {
      setLockedUntil(Date.now() + PIN_LOCKOUT_MS);
      setAttempts(0);
    }
  }

  if (authed) return children;

  return (
    <div className="max-w-sm mx-auto rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 shadow-sm text-center">
      <div className="h-12 w-12 rounded-full bg-indigo-600/10 flex items-center justify-center mx-auto mb-3">
        <Lock className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
      </div>
      <h2 className="text-lg font-semibold">Admin Access Required</h2>
      <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
        Enter the admin PIN to open the scanner. Only trusted staff should have this.
      </p>

      <form onSubmit={handleSubmit} className="mt-5 space-y-3">
        <input
          type="password"
          inputMode="numeric"
          value={pin}
          onChange={(e) => setPin(e.target.value)}
          disabled={locked}
          placeholder="Enter PIN"
          className="w-full text-center tracking-[0.4em] rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500 disabled:opacity-50"
        />
        <button
          type="submit"
          disabled={locked || !pin}
          className="w-full rounded-lg bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white text-sm font-medium py-2.5 transition-colors"
        >
          {locked ? `Locked — try again in ${secondsLeft}s` : "Unlock Scanner"}
        </button>
        {attempts > 0 && !locked && (
          <p className="text-xs text-red-500">Incorrect PIN. {MAX_PIN_ATTEMPTS - attempts} attempt(s) left.</p>
        )}
      </form>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Tab 2 — Admin QR Scanner
// ────────────────────────────────────────────────────────────────────────
const SCANNER_ELEMENT_ID = "qr-scanner-viewport";

function AdminScanner({ resolveScan, commitCheckIn }) {
  return (
    <AdminPinGate>
      <ScannerInner resolveScan={resolveScan} commitCheckIn={commitCheckIn} />
    </AdminPinGate>
  );
}

function ScannerInner({ resolveScan, commitCheckIn }) {
  const [manualMode, setManualMode] = useState(false);
  const [manualInput, setManualInput] = useState("");
  const [cameraError, setCameraError] = useState(null);
  const [isScanning, setIsScanning] = useState(false);
  const [banner, setBanner] = useState(null);
  const [errorModal, setErrorModal] = useState(null); // reason string
  const [confirmTarget, setConfirmTarget] = useState(null); // participant pending confirmation

  const html5QrCodeRef = useRef(null);
  const lastScanRef = useRef({ value: null, at: 0 });
  // A ref instead of state — "busy" only guards against overlapping async
  // resolutions and must NEVER trigger a re-render or effect re-run, since
  // that was exactly what caused the camera to restart mid-initialization
  // and crash with "Cannot stop, scanner is not running or paused."
  const busyRef = useRef(false);
  // html5-qrcode's internal state machine only allows pause()/resume() once
  // start() has truly resolved — track that with a ref too.
  const scannerReadyRef = useRef(false);

  const pauseScanner = useCallback(() => {
    const instance = html5QrCodeRef.current;
    if (instance && scannerReadyRef.current) {
      try {
        instance.pause(true);
      } catch {
        // Ignore — instance may already be stopped/paused.
      }
    }
  }, []);

  const resumeScanner = useCallback(() => {
    const instance = html5QrCodeRef.current;
    if (instance && scannerReadyRef.current) {
      try {
        instance.resume();
      } catch {
        // Ignore — instance may not be in a paused state.
      }
    }
  }, []);

  // Central handler for both camera decodes and manual submissions.
  const handleDecoded = useCallback(
    async (decodedText) => {
      const now = Date.now();
      if (lastScanRef.current.value === decodedText && now - lastScanRef.current.at < 2000) {
        return;
      }
      lastScanRef.current = { value: decodedText, at: now };

      if (busyRef.current) return;
      busyRef.current = true;
      const result = await resolveScan(decodedText);
      busyRef.current = false;

      if (result.status === "pending-confirm") {
        pauseScanner();
        setBanner(null);
        setErrorModal(null);
        setConfirmTarget(result.participant);
      } else if (result.status === "duplicate") {
        playErrorBeep();
        setErrorModal(null);
        setBanner({
          type: "duplicate",
          message: `Already Checked In at ${formatTime(result.participant.checkedInAt)}`,
        });
      } else {
        playErrorBeep();
        setBanner(null);
        setErrorModal(result.reason);
      }
    },
    [resolveScan, pauseScanner]
  );

  // Keep a ref to the latest handleDecoded so the camera-lifecycle effect
  // below never needs handleDecoded in its dependency array. That's the
  // key fix: the effect must only run when manualMode toggles (or on
  // mount/unmount) — not every time internal scan state changes.
  const handleDecodedRef = useRef(handleDecoded);
  useEffect(() => {
    handleDecodedRef.current = handleDecoded;
  }, [handleDecoded]);

  // ── Camera lifecycle ────────────────────────────────────────────────
  useEffect(() => {
    if (manualMode) return;

    let cancelled = false;
    let qr;
    try {
      qr = new Html5Qrcode(SCANNER_ELEMENT_ID);
    } catch (err) {
      setIsScanning(false);
      setCameraError("Could not initialize the scanner: " + (err?.message || String(err)));
      return; // nothing to clean up — constructor never succeeded
    }
    html5QrCodeRef.current = qr;
    scannerReadyRef.current = false;

    qr.start(
      { facingMode: "environment" },
      { fps: 10, qrbox: { width: 250, height: 250 } },
      (decodedText) => {
        if (!cancelled) handleDecodedRef.current(decodedText);
      },
      () => {
        // Per-frame "no QR found" — expected constantly, ignore.
      }
    )
      .then(() => {
        if (!cancelled) {
          scannerReadyRef.current = true;
          setIsScanning(true);
          setCameraError(null);
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setIsScanning(false);
          setCameraError(typeof err === "string" ? err : err?.message || "Camera access denied or unavailable.");
        }
      });

    return () => {
      cancelled = true;
      const instance = html5QrCodeRef.current;
      // stop() throws SYNCHRONOUSLY (not a rejected promise) if start()
      // hadn't fully finished yet — a real try/catch around the call
      // itself is required, a .catch() on the promise chain is not enough.
      if (instance && scannerReadyRef.current) {
        try {
          instance
            .stop()
            .then(() => instance.clear())
            .catch(() => {});
        } catch {
          try {
            instance.clear();
          } catch {
            /* nothing more we can do — instance is being discarded anyway */
          }
        }
      }
      scannerReadyRef.current = false;
      setIsScanning(false);
    };
  }, [manualMode]);

  function handleManualSubmit(e) {
    e.preventDefault();
    if (!manualInput.trim()) return;
    handleDecoded(manualInput.trim());
    setManualInput("");
  }

  function handleConfirm() {
    if (!confirmTarget) return;
    const updated = commitCheckIn(confirmTarget.id);
    setConfirmTarget(null);
    if (updated) {
      playSuccessBeep();
      fireConfetti();
      setBanner({ type: "success", message: `${updated.name} checked in successfully.` });
    }
    resumeScanner();
  }

  function handleReject() {
    setConfirmTarget(null);
    setBanner({ type: "duplicate", message: "Check-in cancelled — photo did not match, or wrong person." });
    resumeScanner();
  }

  return (
    <div className="max-w-2xl mx-auto space-y-4">
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-5 sm:p-6 shadow-sm">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <ScanLine className="h-5 w-5 text-indigo-600 dark:text-indigo-400" />
            Admin QR Scanner
            <ShieldCheck className="h-4 w-4 text-emerald-500" title="Admin session active" />
          </h2>

          <button
            onClick={() => {
              setManualMode((m) => !m);
              setCameraError(null);
              setBanner(null);
              setConfirmTarget(null);
            }}
            className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs font-medium border transition-colors ${
              manualMode ? "bg-indigo-600 text-white border-indigo-600" : "border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800"
            }`}
          >
            <KeyRound className="h-3.5 w-3.5" />
            {manualMode ? "Manual entry ON" : "Simulate manual scan"}
          </button>
        </div>

        {banner && (
          <div
            className={`mt-4 rounded-xl px-4 py-3 flex items-start gap-2.5 text-sm ${
              banner.type === "success"
                ? "bg-emerald-50 text-emerald-800 border border-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-300 dark:border-emerald-500/30"
                : "bg-amber-50 text-amber-800 border border-amber-200 dark:bg-amber-500/10 dark:text-amber-300 dark:border-amber-500/30"
            }`}
          >
            {banner.type === "success" ? <CheckCircle2 className="h-4 w-4 mt-0.5 shrink-0" /> : <AlertTriangle className="h-4 w-4 mt-0.5 shrink-0" />}
            <span>{banner.message}</span>
          </div>
        )}

        {!manualMode ? (
          <div className="mt-4">
            <div id={SCANNER_ELEMENT_ID} className="w-full aspect-square max-w-sm mx-auto rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-slate-950" />
            <div className="mt-3 flex items-center justify-center gap-2 text-xs">
              {isScanning ? (
                <span className="inline-flex items-center gap-1.5 text-emerald-600 dark:text-emerald-400">
                  <Camera className="h-3.5 w-3.5" /> Camera active — point at a QR ticket
                </span>
              ) : cameraError ? (
                <span className="inline-flex items-center gap-1.5 text-red-500">
                  <CameraOff className="h-3.5 w-3.5" /> {cameraError}
                </span>
              ) : (
                <span className="inline-flex items-center gap-1.5 text-slate-400">
                  <Camera className="h-3.5 w-3.5" /> Initializing camera…
                </span>
              )}
            </div>
            {cameraError && (
              <p className="mt-2 text-center text-xs text-slate-500 dark:text-slate-400">
                Camera unavailable. Use{" "}
                <button onClick={() => setManualMode(true)} className="underline text-indigo-600 dark:text-indigo-400">
                  manual entry
                </button>{" "}
                instead.
              </p>
            )}
          </div>
        ) : (
          <form onSubmit={handleManualSubmit} className="mt-4 space-y-3">
            <label className="text-sm font-medium">Paste / type signed QR payload</label>
            <textarea
              value={manualInput}
              onChange={(e) => setManualInput(e.target.value)}
              rows={3}
              placeholder='{"id":"TCK-XXXX","name":"...","email":"...","sig":"..."}'
              className="w-full rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 px-3 py-2 text-sm font-mono outline-none focus:ring-2 focus:ring-indigo-500"
            />
            <p className="text-xs text-slate-400">
              A payload without a valid "sig" field (e.g. hand-typed from a copied ID) will always be rejected.
            </p>
            <button type="submit" className="w-full rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-medium py-2 transition-colors">
              Submit Check-In
            </button>
          </form>
        )}
      </div>

      {confirmTarget && (
        <ConfirmIdentityModal participant={confirmTarget} onConfirm={handleConfirm} onReject={handleReject} />
      )}

      {errorModal && <ErrorModal reason={errorModal} onClose={() => setErrorModal(null)} />}
    </div>
  );
}

// Shows the registered photo big, so the admin can eyeball-match it against
// the person physically holding the QR before attendance is committed.
function ConfirmIdentityModal({ participant, onConfirm, onReject }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4" role="dialog" aria-modal="true">
      <div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 shadow-xl text-center">
        <p className="text-xs font-medium text-indigo-600 dark:text-indigo-400 uppercase tracking-wide">Confirm identity</p>
        <img
          src={participant.photo}
          alt={participant.name}
          className="mx-auto mt-3 h-32 w-32 rounded-2xl object-cover border-2 border-indigo-200 dark:border-indigo-500/40"
        />
        <p className="mt-3 font-semibold text-lg">{participant.name}</p>
        <p className="text-sm text-slate-500 dark:text-slate-400">{participant.email}</p>
        <p className="text-xs font-mono text-slate-400 mt-1">{participant.id}</p>
        <p className="mt-3 text-xs text-slate-500 dark:text-slate-400">
          Does this photo match the person in front of you?
        </p>
        <div className="mt-4 flex gap-2">
          <button onClick={onReject} className="flex-1 rounded-lg border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-sm font-medium py-2 transition-colors">
            Not a match
          </button>
          <button onClick={onConfirm} className="flex-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-medium py-2 transition-colors">
            Confirm &amp; Check In
          </button>
        </div>
      </div>
    </div>
  );
}

function ErrorModal({ reason, onClose }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4" role="dialog" aria-modal="true">
      <div className="w-full max-w-sm rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-6 shadow-xl">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-2 text-red-600 dark:text-red-400">
            <XCircle className="h-5 w-5" />
            <h3 className="font-semibold">Invalid QR Code</h3>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200" aria-label="Close">
            <X className="h-4 w-4" />
          </button>
        </div>
        <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">{reason}</p>
        <button onClick={onClose} className="mt-5 w-full rounded-lg bg-slate-900 dark:bg-slate-100 text-white dark:text-slate-900 text-sm font-medium py-2 hover:opacity-90 transition-opacity">
          Dismiss
        </button>
      </div>
    </div>
  );
}

// ────────────────────────────────────────────────────────────────────────
// Tab 3 — Attendance Dashboard
// ────────────────────────────────────────────────────────────────────────
function AttendanceDashboard({ participants }) {
  const [query, setQuery] = useState("");
  const [filter, setFilter] = useState("all");

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    return participants
      .filter((p) => (filter === "attended" ? p.attended : filter === "pending" ? !p.attended : true))
      .filter((p) => !q || p.name.toLowerCase().includes(q) || p.email.toLowerCase().includes(q) || p.id.toLowerCase().includes(q))
      .sort((a, b) => {
        if (a.attended && b.attended) return new Date(b.checkedInAt) - new Date(a.checkedInAt);
        if (a.attended !== b.attended) return a.attended ? -1 : 1;
        return a.name.localeCompare(b.name);
      });
  }, [participants, query, filter]);

  const filters = [
    { id: "all", label: "All" },
    { id: "attended", label: "Attended" },
    { id: "pending", label: "Pending" },
  ];

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-4 sm:p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between">
          <div className="relative flex-1">
            <Search className="h-4 w-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
            <input
              type="text"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search by name, email, or ticket ID…"
              className="w-full rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 pl-9 pr-3 py-2 text-sm outline-none focus:ring-2 focus:ring-indigo-500"
            />
          </div>
          <div className="flex gap-1 rounded-lg border border-slate-200 dark:border-slate-800 p-1 self-start">
            {filters.map((f) => (
              <button
                key={f.id}
                onClick={() => setFilter(f.id)}
                className={`rounded-md px-3 py-1 text-xs font-medium transition-colors ${
                  filter === f.id ? "bg-indigo-600 text-white" : "text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>
        </div>
      </div>

      <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shadow-sm overflow-hidden">
        {filtered.length === 0 ? (
          <div className="p-10 text-center text-sm text-slate-400">No participants match your search.</div>
        ) : (
          <ul className="divide-y divide-slate-100 dark:divide-slate-800">
            {filtered.map((p) => (
              <li key={p.id} className="flex items-center justify-between gap-3 px-4 sm:px-5 py-3">
                <div className="flex items-center gap-3 min-w-0">
                  {p.photo ? (
                    <img src={p.photo} alt={p.name} className="h-9 w-9 rounded-full object-cover shrink-0 border border-slate-200 dark:border-slate-800" />
                  ) : (
                    <div className="h-9 w-9 rounded-full bg-slate-100 dark:bg-slate-800 shrink-0" />
                  )}
                  <div className="min-w-0">
                    <p className="text-sm font-medium truncate">{p.name}</p>
                    <p className="text-xs text-slate-500 dark:text-slate-400 truncate">
                      {p.email} · <span className="font-mono">{p.id}</span>
                    </p>
                  </div>
                </div>

                <div className="shrink-0 text-right">
                  {p.attended ? (
                    <span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 dark:bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 text-xs font-medium px-2.5 py-1">
                      <CheckCircle2 className="h-3.5 w-3.5" />
                      Attended
                    </span>
                  ) : (
                    <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 text-xs font-medium px-2.5 py-1">
                      Pending
                    </span>
                  )}
                  {p.attended && <p className="text-[11px] text-slate-400 mt-1">{formatTime(p.checkedInAt)}</p>}
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>
    </div>
  );
}
